version: '3.8'
services:
  api:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: api
    ports:
      - 3000:3000
    restart: always
    depends_on:
      - mysql
    networks:
      - app_net
  mysql:
    build:
      context: ./
      dockerfile: Dockerfile.db
    restart: always
    container_name: mysql
    ports:
      - 3306:3306
    networks:
      - app_net

networks:
  app_net:
    driver: bridge
