POST {{host}}/user/signup
Content-Type: application/json

{
  "email": "jongjjang03@naver.com",
  "password": "Wldms0302!",
  "name": "jongho"
}

###

POST {{host}}/user/login
Content-Type: application/json

{
  "email": "jongjjang03@naver.com",
  "password": "Wldms0302!"
}

> {% client.global.set("token", response.body.token) %}

###

GET {{host}}/user
Authorization: Bearer {{token}}
